adjective = input("Enter an adjective:")
adjective2 = input("Enter a second adjective: ")
type_of_bird = input("Enter a type of bird: ")
room_in_a_house = input("Enter a room in a house: ")
past_tense_verb = input("Enter a past tense verb: ")
verb = input("Enter a verb: ")
relatives_name = input("Enter a relatives name: ")
a_liquid = input("Enter a liquid: ")
noun = input("Enter a noun: ")
ing_verb = input("Enter a verb ending in ing: ")
body_part_plural = input("Enter a body part that is plural: ")
plural_noun = input("Enter a plural noun: ")
ing_verb2 = input("Enter a second verb ending in ing: ")
noun2 = input("Enter a second noun: ")

print("It was a " + adjective + " , " + "cold November day.")
print("I woke up to the " + adjective2 + " smell of " + type_of_bird + " roasting in the " + room_in_a_house + " downstairs.")
print("I " + past_tense_verb + " down the stairs to see if I could help " + verb + " the dinner.")
print("My mom said, ""See if "+ relatives_name + " needs a fresh " + noun + " .""")
print("So I carried a tray of glasses full of " + a_liquid + " into the " + ing_verb + " room.")
print("When I got there, I couldn't believe my " + body_part_plural + " !")
print("There were " + plural_noun +" " + ing_verb2 + " on the " + noun2 + " !")


